test

diff --git a/.github/workflows/publish-to-nuget.yml b/.github/workflows/publish-to-nuget.yml
--- a/.github/workflows/publish-to-nuget.yml
+++ b/.github/workflows/publish-to-nuget.yml
@@ -3,10 +3,10 @@ name: Publish Packages
 on:
   push:
     branches: [ "main" ]
-    #paths:
-    #  - 'src/Spoleto.Cryptography.Rsa/**'
-    #  - 'LICENSE'
-    #  - 'README.md'
+    paths:
+      - 'src/Spoleto.Cryptography.Rsa/**'
+      - 'LICENSE'
+      - 'README.md'
       #- 'src/**'
       #- '!src/**.Tests/**'
   pull_request:
@@ -21,12 +21,12 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    #- id: modified
-    #  uses: pheel/path-watcher-action@v1
-    #  with:
-    #      github_token: ${{ secrets.GITHUB_TOKEN }} # no need to set this secret, it is always available!
-    #      paths: 'src/Spoleto.Cryptography.Rsa/**'
-    #      return_files: false # if true, return an array of the modified paths. defaults to false.
+    - id: modified
+      uses: pheel/path-watcher-action@v1
+      with:
+          github_token: ${{ secrets.GITHUB_TOKEN }} # no need to set this secret, it is always available!
+          paths: 'src/Spoleto.Cryptography.Rsa/**'
+          return_files: false # if true, return an array of the modified paths. defaults to false.
   
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
@@ -40,12 +40,12 @@ jobs:
       run: dotnet build --configuration Release --no-restore
 
     - name: Test with the dotnet CLI
-      #if: steps.modified.outputs.modified # run this step if there are changes in the source project
+      if: steps.modified.outputs.modified # run this step if there are changes in the source project
       run: dotnet test --no-restore --logger "trx;LogFileName=test-results.trx"
 
     - name: Tests report
       uses: dorny/test-reporter@v1.5.0
-      if:  ( success() || failure() ) # run this step if there are changes in the source project and even previous step failed
+      if: steps.modified.outputs.modified && ( success() || failure() ) # run this step if there are changes in the source project and even previous step failed
       with:
         name: Test results
         path: '**/test-results.trx'
