tests

diff --git a/.github/workflows/publish-to-nuget.yml b/.github/workflows/publish-to-nuget.yml
--- a/.github/workflows/publish-to-nuget.yml
+++ b/.github/workflows/publish-to-nuget.yml
@@ -24,10 +24,11 @@ jobs:
     - id: modified
       uses: pheel/path-watcher-action@v1
       with:
-          #github_token: ${{ secrets.GITHUB_TOKEN }} # no need to set this secret, it is always available!
+          github_token: ${{ secrets.GITHUB_TOKEN }} # no need to set this secret, it is always available!
           paths: 'src/Spoleto.Cryptography.Rsa/**'
           return_files: false # if true, return an array of the modified paths. defaults to false.
 
+  
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
@@ -39,13 +40,11 @@ jobs:
     - name: Build
       run: dotnet build --configuration Release --no-restore
 
-    - name: Test with the dotnet CLI
-    - if: steps.modified.outputs.modified # run this step if there are changes in the source project
-      run: dotnet test --no-restore --logger "trx;LogFileName=test-results.trx"
+
 
     - name: Tests report
-    - if: steps.modified.outputs.modified && ( success() || failure() ) # run this step if there are changes in the source project and even previous step failed
       uses: dorny/test-reporter@v1.5.0
+    - if: steps.modified.outputs.modified && ( success() || failure() ) # run this step if there are changes in the source project and even previous step failed
       with:
         name: Test results
         path: '**/test-results.trx'
