tests

diff --git a/.github/workflows/publish-to-nuget.yml b/.github/workflows/publish-to-nuget.yml
--- a/.github/workflows/publish-to-nuget.yml
+++ b/.github/workflows/publish-to-nuget.yml
@@ -1,28 +1,56 @@
 name: Publish Packages
 
 on:
-    workflow_run:
-        workflows: ["Run Tests By Logic", "Update README", "Update LICENSE"]
-        branches: [ "main" ]
-        types: 
-            - completed
+  push:
+    branches: [ "main" ]
+    paths:
+      - 'src/Spoleto.Cryptography.Rsa/**'
+      - 'LICENSE'
+      - 'README.md'
+      #- 'src/**'
+      #- '!src/**.Tests/**'
+  pull_request:
+    branches: [ main ]
 
 jobs:
-  build-publish:
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+
+  Build-Tests-Publish:
 
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v3
+
+    - id: modified
+      uses: pheel/path-watcher-action@v1
+      with:
+          #github_token: ${{ secrets.GITHUB_TOKEN }} # no need to set this secret, it is always available!
+          paths: 'src/Spoleto.Cryptography.Rsa/**'
+          return_files: false # if true, return an array of the modified paths. defaults to false.
+
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
-        dotnet-version: 3.1.x
+        dotnet-version: 6.0.x
+
     - name: Restore dependencies
-      run: dotnet restore src/Spoleto.Cryptography.Rsa/Spoleto.Cryptography.Rsa.csproj
+      run: dotnet restore
+
     - name: Build
-      run: dotnet build src/Spoleto.Cryptography.Rsa/Spoleto.Cryptography.Rsa.csproj --configuration Release --no-restore
+      run: dotnet build --configuration Release --no-restore
+
+    - name: Test with the dotnet CLI
+    - if: steps.modified.outputs.modified # run this step if there are changes in the source project
+      run: dotnet test --no-restore --logger "trx;LogFileName=test-results.trx"
+
+    - name: Tests report
+    - if: steps.modified.outputs.modified && ( success() || failure() ) # run this step if there are changes in the source project and even previous step failed
+      uses: dorny/test-reporter@v1.5.0
+      with:
+        name: Test results
+        path: '**/test-results.trx'
+        reporter: dotnet-trx
+
     - name: Publish to Nuget
       uses: brandedoutcast/publish-nuget@v2.5.5
       with:
